### ISSUE TITLE
Error: Cannot find id for mmc block disk device

### ISSUE THREAD

**Issue by l29ah** [pali/0xFFFF#5] opened 2018-02-08 16:24 UTC
```
∞ 0xFFFF -e            
0xFFFF v0.7  // Open Free Fiasco Firmware Flasher

Not a local device

Waiting for USB device...  
Found USB device: RX-51 (0x421:0x1c7) in RAW disk mode
USB device product string: N900 (Storage Mode)
USB device serial number string: 372041756775
Detected USB device: RX-51

Error: Cannot find id for mmc block disk device
Error: No device detected
```

**Comment by pali** [comment] 2018-02-08 16:50
Is this problem also with version from git master branch? Because in commits 27a55c3367a3c66b075a2ef622f6aa1a3d19c24b and 31569c169a94640759a28acd420f27e0f39d9d3f were some fixes related to mmc partition selection.

**Comment by l29ah** [comment] 2018-02-08 16:53
I'm on the master branch.

**Comment by pali** [comment] 2018-02-08 18:30
I found one problem in that code (now fixed in master branch), but seems it is not related to your problem for now. Can you post output of `ls -l /sys/dev/block/` ?

**Comment by l29ah** [comment] 2018-02-08 19:20
```
∞ ls -l /sys/dev/block/   
total 0
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:0 -> ../../devices/virtual/block/ram0
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:1 -> ../../devices/virtual/block/ram1
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:10 -> ../../devices/virtual/block/ram10
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:11 -> ../../devices/virtual/block/ram11
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:12 -> ../../devices/virtual/block/ram12
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:13 -> ../../devices/virtual/block/ram13
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:14 -> ../../devices/virtual/block/ram14
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:15 -> ../../devices/virtual/block/ram15
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:2 -> ../../devices/virtual/block/ram2
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:3 -> ../../devices/virtual/block/ram3
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:4 -> ../../devices/virtual/block/ram4
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:5 -> ../../devices/virtual/block/ram5
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:6 -> ../../devices/virtual/block/ram6
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:7 -> ../../devices/virtual/block/ram7
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:8 -> ../../devices/virtual/block/ram8
lrwxrwxrwx 1 root root 0 Feb  8 19:13 1:9 -> ../../devices/virtual/block/ram9
lrwxrwxrwx 1 root root 0 Feb  8 19:13 7:0 -> ../../devices/virtual/block/loop0
lrwxrwxrwx 1 root root 0 Feb  8 19:13 7:1 -> ../../devices/virtual/block/loop1
lrwxrwxrwx 1 root root 0 Feb  8 19:13 7:2 -> ../../devices/virtual/block/loop2
lrwxrwxrwx 1 root root 0 Feb  8 19:13 7:3 -> ../../devices/virtual/block/loop3
lrwxrwxrwx 1 root root 0 Feb  8 19:13 7:4 -> ../../devices/virtual/block/loop4
lrwxrwxrwx 1 root root 0 Feb  8 19:13 7:5 -> ../../devices/virtual/block/loop5
lrwxrwxrwx 1 root root 0 Feb  8 19:13 7:6 -> ../../devices/virtual/block/loop6
lrwxrwxrwx 1 root root 0 Feb  8 19:13 7:7 -> ../../devices/virtual/block/loop7
lrwxrwxrwx 1 root root 0 Feb  8 02:30 8:0 -> ../../devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda
lrwxrwxrwx 1 root root 0 Feb  8 02:15 8:1 -> ../../devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda1
lrwxrwxrwx 1 root root 0 Feb  8 22:19 8:16 -> ../../devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.0/host6/target6:0:0/6:0:0:0/block/sdb
lrwxrwxrwx 1 root root 0 Feb  8 19:13 8:2 -> ../../devices/pci0000:00/0000:00:1f.2/ata1/host0/target0:0:0/0:0:0:0/block/sda/sda2
lrwxrwxrwx 1 root root 0 Feb  8 22:19 8:32 -> ../../devices/pci0000:00/0000:00:1a.0/usb1/1-1/1-1.2/1-1.2:1.0/host6/target6:0:0/6:0:0:1/block/sdc
```

**Comment by pali** [comment] 2018-02-08 19:26
`8:16` and `8:32` should be devices exported from Nokia N900. What do you have in `busnum` and `devnum` files? E.g. `cat /sys/dev/block/8:16/device/../../../../busnum`

**Comment by l29ah** [comment] 2018-02-08 19:45
On Thu, Feb 08, 2018 at 11:26:51AM -0800, pali wrote:
> `8:16` and `8:32` should be devices exported from Nokia N900. What do you have in `busnum` and `devnum` files? E.g. `cat /sys/dev/block/8:16/device/../../../../busnum`

l29ah-x201 ~ ∞ cat /sys/dev/block/8:16/device/../../../../busnum
1
l29ah-x201 ~ ∞ cat /sys/dev/block/8:16/device/../../../../devnum
22

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by pali** [comment] 2018-02-08 20:01
Ok and what is the output of `lsusb -d 0421:01c7`?

**Comment by l29ah** [comment] 2018-02-08 20:21
On Thu, Feb 08, 2018 at 12:01:16PM -0800, pali wrote:
> Ok and what is the output of `lsusb -d 0421:01c7`?

Bus 001 Device 035: ID 0421:01c7 Nokia Mobile Phones N900 (Storage Mode)

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Comment by l29ah** [comment] 2018-02-08 20:22
(i've reconnected it, now the sysfs nodes show 1 and 35, yes)

**Comment by pali** [comment] 2018-02-08 20:22
That is strange, bus and device numbers from lsusb should correspodent to busnum and devnum...

**Comment by pali** [comment] 2018-02-08 20:23
kernel allocate always some new/free number, but at one connection they should be same

**Comment by l29ah** [comment] 2018-02-08 20:34
they do

**Comment by pali** [comment] 2018-02-08 20:42
That is even more strange... In file src/disk.c is function disk_init() and inside it a while loop which iterates all entries in /sys/dev/block/. For some unknown reason it cannot find entry which would match to busnum/devnum. Are you able to debug it? I thought that problem can be in this part of code:
```
		if ( devnum != device->devnum || device->bus->location != busnum )
			continue;
```
Buf if you say that devnum/busnum in /sys and lsusb matches, then I have no idea :-(

I'm not able to reproduce this problem with my Nokia N900.

**Comment by l29ah** [comment] 2018-02-08 20:59
(gdb) p device->bus->location
$10 = 0

libusb-0.1.12

**Comment by pali** [comment] 2018-02-08 22:03
Ok, I found where is the problem. Original linux version of libusb-0.1.12 has a bug that `bus->location` is not filled. Debian for a long time has a patch for it: https://sources.debian.org/patches/libusb/2:0.1.12-31/08_bus_location.diff/
(fixed in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=611958)

But it looks like that `bus->dirname` should be filled. Can you check it?

**Comment by l29ah** [comment] 2018-02-08 22:12
On Thu, Feb 08, 2018 at 02:03:58PM -0800, pali wrote:
> Ok, I found where is the problem. Original linux version of libusb-0.1.12 has a bug that `bus->location` is not filled. Debian for a long time has a patch for it: https://sources.debian.org/patches/libusb/2:0.1.12-31/08_bus_location.diff/

Thanks!

> (fixed in https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=611958)
> But it looks like that `bus->dirname` should be filled. Can you check it?

dirname = "001"

-- 
()  ascii ribbon campaign - against html mail
/\  http://arc.pasp.de/   - against proprietary attachments

**Closed as completed** 2018-02-08 22:22 UTC

**Comment by pali** [comment] 2018-02-08 22:23
Fix is now in master branch. Now 0xFFFF should be able to find block device.
